### ISSUE TITLE
Actions are still referring to "distroless/actions" instead of "chainguard-images/actions"?

### ISSUE THREAD

**Issue by kastl-ars** [chainguard-images/actions#139]
Hi,

not sure if this is intentional or just a leftover, but the action READMEs still contain references to the `distroless/actions` repository.

E.g. here:

[`uses: distroless/actions/apko-publish@main`](https://github.com/chainguard-images/actions/blob/main/apko-publish/README.md?plain=1#L8)

Kind Regards,
Johannes

**Comment by cpanato** [comment]
was not, we move from another org, will update
