### ISSUE TITLE
Using multiple tags with apko-publish?

### ISSUE THREAD

**Issue by kastl-ars** [chainguard-images/actions#141]
Hi again,

is it possible to use multiple tags with the apko-publish action? Using two instances of the action would build the image twice, I guess.

Something like this:

```
    tag:
      - ghcr.io/chainguard-dev/apko-example:latest
      - ghcr.io/chainguard-dev/apko-example:1.2.3
```

Thanks in advance,
Johannes

**Comment by cpanato** [comment]
did you try passing as `ghcr.io/chainguard-dev/apko-example:latest, ghcr.io/chainguard-dev/apko-example:1.2.3`?

**Comment by cpanato** [comment]
i think that will not work, but never tested to be honest

**Comment by kastl-ars** [comment]
Huh, apparently this worked:

- https://github.com/kastl-ars/wolfi-renovate-nodejs-bash-git/actions/runs/9269422342/job/25500187992
- https://github.com/kastl-ars/wolfi-renovate-nodejs-bash-git/pkgs/container/wolfi-renovate-nodejs-bash-git/versions

The image is tagged both latest and `:22`

I can prepare a PR to adapt the documentation accordingly, if desired?

**Comment by neumayr** [comment]
just fyi, this is already working:

```
    tag: >-
      ghcr.io/chainguard-dev/apko-example:latest
      ghcr.io/chainguard-dev/apko-example:1.2.3
```

📖 YAML Multiline Docs - https://yaml-multiline.info/
