### ISSUE TITLE
apko-publish action fails with error "touch: /home/runner/work/actions/actions/digest: No such file or directory"

### ISSUE THREAD

**Issue by emosbaugh** [chainguard-images/actions#160]
**Description**

chainguard-images/actions/apko-publish fails with the following error:

```
touch: /home/runner/work/actions/actions/digest: No such file or directory
```

Looks related to this commit.

https://github.com/chainguard-images/actions/commit/9bfa85dc226a6b2818bd1a7a4367ae43840f2af4

**Comment by emosbaugh** [comment]
I've worked around this for now by pinning

```
    - uses: chainguard-images/actions/apko-publish@49e3bc2feb790da6c3a7f749b38c769174c4ad54
      with:
        apko-image: ghcr.io/wolfi-dev/sdk@sha256:b3c690e2aff7a6e6259632047b5d6133169204f7011b9936731cf3f403d5a8c1
```

**Comment by cpanato** [comment]
fixed, see example wf: https://github.com/cpanato/testing-ci-providers/actions/runs/12391538792/job/34588836460
