### ISSUE TITLE
tags workflow wipes out apko.images file

### ISSUE THREAD

**Issue by jdolitsky** [chainguard-images/actions#51]
Since #47 , the file `apko.images` goes missing:
```
Run cat apko.images | sed 's/$/\n/g' | grep -v '^$' | jq -R -s -c 'split("\n")[:-1]' | jq .
cat: apko.images: No such file or directory
[]
cat: apko.images: No such file or directory
```

maybe something related to git checkout

cc @priyawadhwa

**Comment by priyawadhwa** [comment]
Thank you @jdolitsky for debugging and fixing this! I checked the other repos to make sure "additional tags" wasn't causing this bug, looks like these repos are all clear (a lot of them actually don't run the tags workflow which I'll try to add in!) 

- go
- python
- gcc-glibc
- sdk
- busybox
- gcc-musl
- musl-dynamic
- static
- alpine-base
- jdk

**Comment by patflynn** [comment]
good to close?

**Comment by jdolitsky** [comment]
closing as old/inactive. please re-open if necessary
